name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run Maven build
    - name: Build with Maven
      run: mvn clean install

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: mvn test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Integration Tests
      run: mvn verify -Pintegration-tests

  system-tests:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run System Tests
      run: mvn verify -Psystem-tests

  acceptance-tests:
    runs-on: ubuntu-latest
    needs: system-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Acceptance Tests
      run: mvn verify -Pacceptance-tests

  deployment:
    runs-on: ubuntu-latest
    needs: acceptance-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Application
      run: ./deploy.sh