name: Build and Deploy Machine Learning Project

on:
  push:
    branches:
      - '**'

jobs:
  pre-build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Application
      run: echo "pre build stage"

  build:
    runs-on: ubuntu-24.04
    needs: pre-build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

  model-validation:
    runs-on: ubuntu-24.04
    needs: unit-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate Model
      run: echo "Validating model after unit tests and successful build"

  unit-tests:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: mvn test

  integration-tests:
    runs-on: ubuntu-24.04
    needs: unit-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Integration Tests
      run: mvn verify -Pintegration-tests

  system-tests:
    runs-on: ubuntu-24.04
    needs: QualityAssessment-deployment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run System Tests
      run: mvn verify -Psystem-tests

  acceptance-tests:
    runs-on: ubuntu-24.04
    needs: system-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Acceptance Tests
      run: mvn verify -Pacceptance-tests

  Packaging-artifacts:
    runs-on: ubuntu-24.04
    needs: integration-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Packaging-artifacts
      run: echo "Packaging artifacts before Deploying to Quality Assurance"

  Upload-artifact-nexus:
    runs-on: ubuntu-24.04
    needs: Packaging-artifacts

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Packaging-artifacts
      run: echo "storing artifacts for deployment"

  QualityAssessment-deployment:
    runs-on: ubuntu-24.04
    needs: Packaging-artifacts

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to QualityAssessment
      run: echo "Deploying to QA"

  staging-deployment:
    runs-on: ubuntu-24.04
    needs: acceptance-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Staging
      run: echo "Deploying to Staging"

  production-deployment:
    runs-on: ubuntu-24.04
    needs: staging-deployment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Production
      run: echo "Deploying to Production"